import { useEffect, useState } from "@wordpress/element";
import { AuditProvider, useAudit } from "../context/AuditContext";
import Step7_Results from "./Step7_Results";

/**
 * ResultsViewer
 *
 * Admin-only page that decodes a base64 ?d= URL parameter and renders
 * Step7_Results exactly as the user saw it — zero code duplication.
 *
 * URL format (generated by Step6_Goal.jsx):
 *   /rental-audit-results/?d=BASE64_ENCODED_JSON
 *
 * Access control:
 *   • Server-side: WordPress page template checks is_user_logged_in()
 *     && current_user_can('manage_options') — redirects to /wp-admin/ if not.
 *   • Client-side: checks window.rentalAuditConfig.isAdmin — shows an error
 *     screen if somehow reached without admin privileges.
 *
 * This component is mounted on the results viewer WordPress page,
 * NOT inside the main audit widget. It has its own <AuditProvider> wrapper
 * so it is completely isolated from the main audit form.
 */

// ── Inner component — reads context, decodes URL, hydrates state ─────────────
const ViewerInner = () => {
  const { update } = useAudit();
  const [error, setError] = useState("");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    // ── Admin guard (client-side) ──────────────────────────────────────────
    const isAdmin = window?.rentalAuditConfig?.isAdmin ?? false;
    if (!isAdmin) {
      setError(
        "Access denied. You must be logged in as an administrator to view this page.",
      );
      return;
    }

    // ── Decode the ?d= param ───────────────────────────────────────────────
    const params = new URLSearchParams(window.location.search);
    const encoded = params.get("d");

    if (!encoded) {
      setError(
        "No audit data found in URL. Please use the link from the FluentCRM contact record.",
      );
      return;
    }

    try {
      const json = decodeURIComponent(escape(atob(encoded)));
      const payload = JSON.parse(json);

      // Hydrate just the fields Step7_Results reads from state.auditResults
      update({
        auditResults: payload,
        // Also set address so the admin sees it in context (Step7 doesn't
        // render it directly but it's useful for debugging)
        address: payload.address ?? "",
      });

      setReady(true);
    } catch (e) {
      setError(
        "Could not decode audit data. The link may be corrupted or incomplete.",
      );
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Error state ───────────────────────────────────────────────────────────
  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#F7F5F0] p-8">
        <div className="max-w-md text-center">
          <div className="w-14 h-14 rounded-full bg-red-100 flex items-center justify-center mx-auto mb-4">
            <span className="text-red-500 text-2xl">✕</span>
          </div>
          <h2 className="text-xl font-bold text-brand-black mb-2">
            Unable to load audit
          </h2>
          <p className="text-sm text-audit-neutral">{error}</p>
        </div>
      </div>
    );
  }

  // ── Loading state ─────────────────────────────────────────────────────────
  if (!ready) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#F7F5F0]">
        <p className="text-sm font-bold tracking-widest uppercase text-audit-neutral animate-pulse">
          Loading audit results…
        </p>
      </div>
    );
  }

  // ── Results — re-use Step7_Results exactly as-is ─────────────────────────
  // goTo(8) button in Step7_Results is hidden in viewer mode via the
  // ra-viewer class on the wrapper — add CSS: .ra-viewer button[data-goto="8"] { display:none }
  // Or simply: the "Get My Full Strategy Plan" button is inert in this context
  // since the user has already submitted. We wrap with a note for the admin.
  // In ResultsViewer.jsx, replace the return in ViewerInner:
  return (
    <div className="min-h-[75dvh] bg-step-bg flex items-start md:items-center justify-center py-12 px-4 font-sans">
      <div className="w-full max-w-4xl">
        {/* Admin banner */}
        <div className="bg-[#1e1e2e] text-white px-6 py-3 flex items-center gap-3 text-xs font-bold tracking-widest uppercase rounded-t-[24px]">
          <span className="text-brand-gold">👁 Admin View</span>
        </div>

        {/* Same card wrapper as App.js */}
        <div className="bg-step-card rounded-b-[24px] shadow-card overflow-hidden ra-viewer">
          <style>{`.ra-viewer button[class*="bg-[#3D2E14]"] { display: none !important; }`}</style>
          <style>{`[data-viewer-hide] { display: none !important; }`}</style>
          <Step7_Results />
        </div>
      </div>
    </div>
  );
};

// ── Root export — wraps with its own AuditProvider ───────────────────────────
const ResultsViewer = () => (
  <AuditProvider>
    <ViewerInner />
  </AuditProvider>
);

export default ResultsViewer;
